### PR TITLE
Change setup.py to package enough into tarball to build from source

### PR DESCRIPTION
**Pull request by ndmaxar**
Was initially missing *.pxd files. Need to package C++ header file as well. And also include the numpy info in the extension is moved.

### CODE REVIEW

**Comment by ndmaxar** [comment]
@martinResearch this will help us get deodr into the conda forge.  I don't think this will affect other things but let me know if it does.

**Comment by martinResearch** [comment]
@ndmaxar  , the build test are failing , not sure what is wrong. We will need to fix that first.

**Comment by ndmaxar** [comment]
@martinResearch I've udpated it and the current error is 
`python -m twine upload wheelhouse/*.whl --skip-existing -p %encrypted_pypi_api_token%`. Which I don't think I have control over.

**Comment by oblute** [comment]
@martinResearch we were able to patch the released tarball to include the necessary files/adjust the setup, and we have it building from source on a PR for the conda-forge https://github.com/conda-forge/staged-recipes/pull/12772 thanks for all of your help!

**Comment by martinResearch** [comment]
Great. I have a PR about to get in that adds the missing DifferentiableRenderer.h to the tar.gz ball and upload to source wheel to pypi. https://github.com/martinResearch/DEODR/pull/33. I do not copy numpy headers as I believe it should not be included in my source wheel. So that should work for future releases.

**Comment by martinResearch** [comment]
@ndmaxar , yes appveyor fails when trying to upload with twine the wheel during the PR tests, complaining about missing password, but that works in the main branch, not sure why so I just ignore these errors. Not sure how to fix that. Anyway , do you still need this PR in ? or is  https://github.com/martinResearch/DEODR/pull/33 fixing you problem ? the tar gz file here https://ci.appveyor.com/project/martinResearch/deodr/builds/35520204/job/amt6r0a1xju4re8o/artifacts contains the DifferentiableRenderer.h file. Is that solving your problem ?

**Comment by martinResearch** [comment]
@oblute do you know if there is a way to automatize the publication of future revisions on conda forge ? I am now publishing the tar.gz file on pypi.org , would that help ?

**Comment by ndmaxar** [comment]
@martinResearch with #33 this PR isn't needed, so closing now.

**Pull request closed without merging**
